title: Ricardo I. Maya # your name (or website title) here
logo: "/images/rickprofilephoto2.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Chicago Native, Bred & Born. 
  <br><br>
  Jr. Web Developer 
  <br><br>
  <a href="https://www.linkedin.com/in/rickmaya/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
